dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.0.0-p647
  - 2.3.4
  - 2.4.1

branches:
  only:
    - master
    - /.+-stable$/

before_install:
  # There is a bug in travis. When using system ruby, bundler is not
  # installed and causes the default install action to fail.
  - if [ "$TRAVIS_RUBY_VERSION" = "system" ]; then sudo gem install "bundler:~> 1.16" --conservative; else gem install "bundler:~> 1.16" --conservative; fi
  # RubyGems 2.0.14 isn't a fun time on 2.0.0p451
  - if [ "$TRAVIS_RUBY_VERSION" = "system" ]; then sudo gem update --system; fi
